// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemoteAc.Infrastructure.Context;

#nullable disable

namespace RemoteAc.Infrastructure.Migrations
{
    [DbContext(typeof(RemoteAcContext))]
    [Migration("20250419160708_Add_Mac_SensorClient")]
    partial class Add_Mac_SensorClient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("RemoteAc.Core.Entities.AppState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AcUnitOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeatherStation")
                        .HasColumnType("TEXT");

                    b.Property<string>("WxGridPoints")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppState");
                });

            modelBuilder.Entity("RemoteAc.Core.Entities.DhtSensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double>("TempC")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "temperature");

                    b.HasKey("Id");

                    b.ToTable("DhtSensorData");
                });

            modelBuilder.Entity("RemoteAc.Core.Entities.SensorClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SensorClients");
                });
#pragma warning restore 612, 618
        }
    }
}
