name: Django CI

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/django.yml'
      - 'ac_ctl_web/**'
      - 'backend/**'
      - 'services/**'
      - 'utilities/**'
      - 'manage.py'
      - 'Pipfile'
      - 'Pipfile.lock'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/django.yml'
      - 'ac_ctl_web/**'
      - 'backend/**'
      - 'services/**'
      - 'utilities/**'
      - 'manage.py'
      - 'Pipfile'
      - 'Pipfile.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pipenv'
      - name: Install Pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Setup environment
        run: |
          echo "$DJANGO_ENV" >> ac_ctl_web/env.py
        env:
          DJANGO_ENV: ${{secrets.DJANGO_ENV}}
      - name: Run Tests
        run: |
          pipenv run python manage.py test
      - name: Check migrations
        run: |
          pipenv run python manage.py makemigrations --check
          pipenv run python manage.py migrate
          
